### ISSUE TITLE
Reviewer availability

### ISSUE THREAD

**Issue by gaearon** [reactjs/ru.reactjs.org#102]
Хотел просто сказать, что на этой неделе буду занят и не смогу ревьюить — так что доверяю @lex111 и @another-guy трясти переводы на тему упрощения. Поменьше существительных и деревянных оборотов, побольше живого языка!  Думаю, в ревью имеет смысл ссылаться на прошлые переводы и процесс, который они прошли: https://github.com/reactjs/ru.reactjs.org/pull/17, https://github.com/reactjs/ru.reactjs.org/pull/42, https://github.com/reactjs/ru.reactjs.org/pull/39.

Можно в этот тред писать, когда кто-то временно не может ревьюить. Чтобы другие были в курсе и можно было перехватить работу.

**Comment by another-guy** [comment]
@lex111 я буду ревьють, что смогу, по вечерам Pacific Standard Time. Но я не буду мёрджить ничего, потому что у меня недостаточно опыта open-source contribution вообще и перевода документации в частности.

**Comment by lex111** [comment]
@another-guy в целом, можно застоппить PR, пока их не посмотрит @gaearon, либо закоммитить, но отметить, что нужно вычитать...

**Comment by another-guy** [comment]
@lex111 "закоммитить" ??? 😕 🤷‍♂️ 

Себе я ставлю задачу максимально вычистить тексты по стилю, чтобы на долю @gaearon остался тот минимум, который ты или я не обнаружили или не смогли разрешить. Иными словами, мёрдж не самоцель, как бы.

**Comment by lex111** [comment]
>   В смысле "зааппрувить"?

Ну да ¯\_(ツ)_/¯

Поэтому я предложил второй вариант..

**Comment by lex111** [comment]
Выхожу на неопределенный срок из проекта. Пожалуйста, доведите до конца перевод, сегодня еще про разделение кода перевод пришлют, это будет последний из важный, остальные страницы в низком приоритете. Так что нам осталось совсем немного до официального запуска, было бы хорошо это сделать на этой неделе.
Тогда в этом ишью https://github.com/reactjs/ru.reactjs.org/issues/235 отметите оставшиеся галочки и закройте ее, чтобы куратор переводов был в курсе, что основная работа завершена. Всем удачи, не оставляйте документацию на долгое время без активности!

**Comment by another-guy** [comment]
@lex111, спасибо за heads up и за все усилия приложенные как к ревью, так и к организации процесса! 🥇
