### ISSUE TITLE
Терминология: Refs forwarding

### ISSUE THREAD

**Issue by Heegiiny** [reactjs/ru.reactjs.org#105]
Есть варианты перевода: перенаправление, проброс, передача. Мне больше нравится перенаправление по аналогии с Port Forwarding.

**Comment by gaearon** [comment]
Я бы ок с перенаправлением.

**Comment by Heegiiny** [comment]
Ок, сразу же ещё вопрос: "Forwarding refs to DOM components" - "Передача рефа компоненту DOM" или "Передача рефа в компонент DOM"?

**Comment by gaearon** [comment]
в DOM-компоненты?

**Comment by Heegiiny** [comment]
Хорошо, множественное число не заметил просто. А native `button` DOM element мы как переводим? Нативный DOM-элемент `button`? Простой (обычный, обыкновенный) DOM-элемент `button`?

**Comment by lex111** [comment]
Так передача или перенаправление?

**Comment by Heegiiny** [comment]
Перенаправление

**Comment by lex111** [comment]
> Ок, сразу же ещё вопрос: "Forwarding refs to DOM components" - "**Передача** рефа компоненту DOM" или "**Передача** рефа в компонент DOM"?

Противоречие?

**Comment by Heegiiny** [comment]
Да, там перенаправление должно быть, ошибся когда писал сообщение. Вопрос был "в компонент" или "компоненту".

**Comment by lex111** [comment]
Хорошо.

> native

_Нативный_, много так кто переводит, предлагаю поступить аналогично. Хотя есть подходящее на русском — _встроенный_ или _собственный_, может как синонимы использовать? Хотя учитывая, что  _native_ редко встречается в тексте, то использовать первый вариант.

**Comment by Heegiiny** [comment]
Ок, спасибо.

**Comment by another-guy** [comment]
@lex111 _встроенный_ или _собственный_ теряют часть содержания. Слово "родной" работает лучше, но "нативный" настолько же узнаваемо, насколько и "коммит". Так я  тоже за транслитерированный вариант.

**Comment by lex111** [comment]
Ок, не забыть только сделать PR.

**Comment by another-guy** [comment]
@lex111 надо завести ишью про бэктрэкинг таких вещей, которые уже могли быть смёржены в `master`?

**Comment by lex111** [comment]
Либо доп. ярлык, типа `need confirm`?

**Comment by another-guy** [comment]
`need confirm` не указывает, что именно искать, усложняя тем самым работу -- надо держать в голове _весь_ глоссарий сразу. Можно, конечно, попробовать и так.

**Comment by lex111** [comment]
Ан извините, имел в виду эту [ишью](https://github.com/reactjs/ru.reactjs.org/issues/102) :face_with_head_bandage: 

> надо завести ишью про бэктрэкинг таких вещей, которые уже могли быть смёржены в `master`? A la "вычитка: term-x"

Что-то не понял :( мы хотим проверям переводы на соответствие глоссарию?

**Comment by another-guy** [comment]
@lex111  мы нечаянно смешали два вопроса, похоже.

1. Про `need confirm` ты мне прояснил, и я за эту идею.

2.  > мы хотим проверям переводы на соответствие глоссарию?

Да, это то, что меня немного волнует.

**Comment by lex111** [comment]
Лучше стараться на этапе принятия PR максимально всё проверять (не менее двух-трёх аппрувов мейнтейнеров); термин впоследствии может измениться, но тогда в PR термина пройтись по переведённым материалам и сделать замену.

**Comment by another-guy** [comment]
@lex111 разумеется, это поможет с минимизацией работы. Но это совсем не гарантирует её сведение к нулю. Всё равно потребуется вычитка, я считаю.

**Comment by Heegiiny** [comment]
Переводим ли мы аббревиатуру HOC?

**Comment by lex111** [comment]
В #103 было небольшое обсуждение.

Если иметь в виду где используется явно аббревиатура, например в заголовке:

> Use HOCs For Cross-Cutting Concerns

То не думаю, что стоит её раскрывать, хочется чтобы заголовки были краткими. Предлагаю просто писать "Используем HOC...", да, пропадает множественное число, но ведь смысл тот же, в русском мы так не можем сделать, поэтому, как по мне, вполне норм. Или нет?

**Comment by Heegiiny** [comment]
Да, нашёл как раз обсуждение HOC устраивает вполне, интересовал именно стандарт в переводе. Мне кажется, можно всё таки оставить `| HOC | HOC |` в таблице.

**Comment by lex111** [comment]
А зачем? Тогда вернее было `| HOCs | HOC |`
Но я предлагаю такой вариант: того, чего нет в этой таблице, то это не переводится. Или даже более частное правило: аббревиатуры не раскрываются/переводятся.

**Comment by Heegiiny** [comment]
> аббревиатуры не раскрываются/переводятся

Тогда стоит добавить в правила.

**Comment by another-guy** [comment]
> Или даже более частное правило: аббревиатуры не раскрываются/переводятся.

Нравится. Потому что есть явный квалификатор -- аббревиатуры.

> Но я предлагаю такой вариант: того, чего нет в этой таблице, то это не переводится.

Очень не нравится. Откуда переводчику знать, на какие слова это распространяется, а на какие -- нет.

**Comment by lex111** [comment]
Понимаю, можно после заголовка "Соглашение по переводу" добавить заметку.

**Comment by Heegiiny** [comment]
> `React.forwardRef` accepts a render function. 
render function не особенно понятно как перевести. Функция-рендерер, функция рендеринга, рендерящая функция?

**Comment by lex111** [comment]
> функция рендеринга

:+1:
