### ISSUE TITLE
Написание названий технологий, продуктов и т.д.

### ISSUE THREAD

**Issue by lex111** [reactjs/ru.reactjs.org#109]
В #97 заметил что названия продуктов, технологий и прочего пишется по-русски:

> Jest -> Джест
> Facebook -> Фейсбук 
> JavaScript -> Джаваскрипт

Я в целом против этого, в документации это вредно, но хочется узнать мнение других участников, и зафиксировать решение в местном руководстве.

**Comment by another-guy** [comment]
Однозначно непереводные слова, мне кажется. По тексту [словаря Web-стандартов](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md) это только подтверждается.

Мы же не хотим ЦСС, ЦэЭсЭС, или СиЭсЭс, правда? 🙅‍♂️

**Comment by lex111** [comment]
Помню так Дэн в начале писал, и так делает в своём блоге, что мне на самом деле нравится, т.е. в публицистке и прочем такого мне даже это нравится (в меру), но не в документации или книгах, посколку может запутывает людей, не говоря уже о том, как это выглядит в случае аббревиатур.

Тогда нужно внести в файлик соответствующее правило.

**Comment by LFedorov** [comment]
Поддержу, перевод собственных имен очень сильно сбивает с толку.

**Comment by lex111** [comment]
@LFedorov не желаете создать PR? :)

**Comment by LFedorov** [comment]
#123
