### ISSUE TITLE
Терминология: folder

### ISSUE THREAD

**Issue by lex111** [reactjs/ru.reactjs.org#113]
Папка, а может быть директория? Может, это очевидно, но нравится последний вариант, но хотелось услышать другие мнения.

**Comment by Heegiiny** [comment]
Можно ещё каталог. Но в английском же также используются оба слова. Если в оригинале folder, то переводить как папка будет логичнее.

**Comment by another-guy** [comment]
@lex111 перевод немного OS-specific. В Win это _папка_ или _каталог_ как правило. В других ОС, чаще _директория_. Мне кажется, что _папка_, что _каталог_ оба узнаваемы. Дословно, folder это, конечно же, _папка_.

**Comment by lex111** [comment]
Ок, тогда не вижу смысл заносить в словарь (поскольк это дословно), просто хотелось узнать мнение остальных.

**Comment by another-guy** [comment]
@lex111 в глоссарий заносить смысл _есть_, как раз потому что вопрос возник. Мы хотим последовательные переводы слов, не?

**Comment by lex111** [comment]
Понял, просто у всех на слуху _очевидный_ перевод, это со мной что-то не так, ок, внесём.
