### ISSUE TITLE
Нужна помощь с термином Cross-Cutting Concerns

### ISSUE THREAD

**Issue by agoldis** [reactjs/ru.reactjs.org#114]
Помогите плз с термином Cross-Cutting Concerns

в контексте:
- Use HOCs For Cross-Cutting Concerns
- We previously recommended mixins as a way to handle cross-cutting concerns.

**Comment by lex111** [comment]
> Cross-Cutting Concerns

Сквозная/общая/разделяемая функциональность?

**Comment by agoldis** [comment]
Сквозная функциональность [wiki](https://ru.wikipedia.org/wiki/%D0%90%D1%81%D0%BF%D0%B5%D0%BA%D1%82%D0%BD%D0%BE-%D0%BE%D1%80%D0%B8%D0%B5%D0%BD%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)
