### ISSUE TITLE
Терминология: snapshot

### ISSUE THREAD

**Issue by gcor** [reactjs/ru.reactjs.org#127]
Снимок
Снепшот
Снэпшот

**Comment by another-guy** [comment]
Я за "снимки", потому что 

> The term was coined as an analogy to that in photography. (Wikipedia)

Это слово легко находится в статьях на русском о React. На втором месте -- _слепок_.

Я не вижу причин для транслитерации (_Снепшот_) в этом конкретном случае. А в _Снэпшот_ используется "э", которую я люблю, но которая нарушает правила русского языка.
