### ISSUE TITLE
Use squash for merging

### ISSUE THREAD

**Issue by vvscode** [reactjs/ru.reactjs.org#128]
Как на счет squash при мерже PR . ? чтобы держать историю чистой

**Comment by another-guy** [comment]
В моём понимании чище как раз `rebase` (потому что потом можно `revert` более мелкие изменения), но я не знаю, как оно по жизни чаще делается в GitHub. Что-то мне подсказывает, что кнопка сделана как "Rebase and merge" по дефолту неспроста... 🤷‍♂️

**Comment by vvscode** [comment]
Я при переводе делаю несколько коммитов - для чистоты с rebase мне нужно делать squash ( ну или --ammend / --force push )

Какая кнопка используется по-дефолту настраивается в свойства репозитория

Про мелкие изменения - для того и ревью в PR, ну и давайте честно, если вы строчку захотите откатить, это проще сделать коммитом, а не ревертом

**Comment by another-guy** [comment]
> Я при переводе делаю несколько коммитов - для чистоты с rebase мне нужно делать squash ( ну или --ammend / --force push )

Мне кажется, у разных людей -- разный workflow.

> Какая кнопка используется по-дефолту настраивается в свойства репозитория

Я не знал об этом до сегодня. 😃 

> Про мелкие изменения - для того и ревью в PR, ну и давайте честно, если вы строчку захотите откатить, это проще сделать коммитом, а не ревертом

Пожалуй, соглашусь тут.

---

Если честно, я немного devil's advocate сейчас. На самом деле, у меня нет преференций сильных...

**Comment by another-guy** [comment]
@lex111 any thoughts on that?

**Comment by lex111** [comment]
Не задумался об этом, да и на самом деле для меня это слишком критично, в оригинальной документации коммиты не объединяются в один, и вроде ничего страшного.  Меня больше "пугает", когда делают force-пуш, но хорошо хоть гитхаб с некоторого времени научился их показывать, раньше вообще можно отправить так изменения, и неудомевать, почему при первом ревью ты видел совершенно иное.
