### ISSUE TITLE
Терминология: Effect Hook, State Hook, Context Hook

### ISSUE THREAD

**Issue by pavelkeyzik** [reactjs/ru.reactjs.org#132]
Есть вариант перевода от @gaearon "эффект-хуков".

**Comment by another-guy** [comment]
Мне кажется, тут английский порядок слов выходит, а по-русски:

> хуков-эффектов
> хуков эффектов
> хук-эффект

Какой вариант лучше, я не знаю. Ещё советую не забывать о втором хуке, который подробно разбирается -- State Hook. Давайте подберём перевод сразу им обоим?

**Comment by ModPhoenix** [comment]
Мне пока нравится:

> хук-состояние или хук-состояния
> хук-эффект
> хук-контекст

или:

> хук-состояние
> эффект хук
> контекст хук

**Comment by another-guy** [comment]
@ModPhoenix 

Вот эти три
> хук-состояние
> хук-эффект
> хук-контекст

были бы консистентны между собой, помимо того что близки к правилам русского языка.

**Comment by lex111** [comment]
А почему не хук состояния, хук эффекта и т.д.? Это ведь определенные хуки, по аналогии с функция рендеринга, а не функция-рендер, или нет? Хотя оба варианта - ок, но зачем такое "усложнение"?

**Comment by another-guy** [comment]
@lex111 на самом деле, я с тобой полностью согласен. Я так и переводил хук состояния.

Мне кажется, что ноги этого ишью растут из комментария @gaearon, который я не могу найти (а был ли "мальчик"?). Дэн несколько раз ссылался на Нору Галь. Она говорит, что цепочки существительных это как бы text smell. Особенно там, где родительный падеж участвует. Наверное, хуки состояния/эффектов/контекста поэтому выглядят для некоторых (но не для меня) коряво.

**Comment by lex111** [comment]
Я помню был в одном из PR, но выглядит странно, так что я бы не заморачивался здесь и использовал привычную структуру. Но хочется получить ещё фидбек на этот счёт.

**Comment by pavelkeyzik** [comment]
@lex111 issue создал основываясь на этом комментарии https://github.com/reactjs/ru.reactjs.org/pull/84#discussion_r256124607

**Comment by lex111** [comment]
Так смысл другой совершенно:

> использование эффект хуков

Ясно, но считаю, что теперь понятно, что лучше всгео написать так:

> использование хука эффектов

**Comment by another-guy** [comment]
Ну, так что, если ли решение?
Переводим как _хук состояния/эффекта/контекста_ (в два слова, без дефиса)?

**Comment by lex111** [comment]
Я считаю, да, именно так.
