### ISSUE TITLE
Терминология: TLDR

### ISSUE THREAD

**Issue by pavelkeyzik** [reactjs/ru.reactjs.org#133]
Есть ли варианты перевода или лучше оставить как есть?

**Comment by another-guy** [comment]
[Wikipedia говорит TL;DR как есть](https://ru.wikipedia.org/wiki/TL;DR).

А ещё, она говорит

> Аналогичное выражение в русском интернет-жаргоне - "ниасилил, многабукаф".

...которые, как я понимаю, приходят из _«олбанского» йезыга_, а значит, совершенно неуместны.

**Comment by pavelkeyzik** [comment]
> В крайнем случае, оставить _TLDR_ как есть.

Из всех вариантов мне пока больше всего нравится этот. Как по мне так короче и не сильно отвлекает. Но раньше меня TL;DR отвлекало, потому что я думал, что это в коде ошибка и что-то лишнее выводится, когда не знаел про значение этого сокращения 😄

**Comment by lex111** [comment]
Согласен с тем, чтобы не переводить.

**Comment by gaearon** [comment]
Можно "вкратце" или "в двух словах"

**Comment by lex111** [comment]
Классные варианты, может, тогда будем переводим?

**Comment by lex111** [comment]
"вкратце" хорошо подходит, одно слово, что хорошо, посколку после TLDR может следовать длинный заголовок.
