### ISSUE TITLE
Терминология: array/object destructuring

### ISSUE THREAD

**Issue by another-guy** [reactjs/ru.reactjs.org#138]
Какого варианта мне придерживаться в #134?

В [MDN](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#%D0%A0%D0%B0%D0%B7%D0%B1%D0%BE%D1%80_%D0%BC%D0%B0%D1%81%D1%81%D0%B8%D0%B2%D0%BE%D0%B2):

> _Разбор массивов_

В комментарии к [PR #65](https://github.com/reactjs/ru.reactjs.org/pull/65#discussion_r256226408)

> деструктуризация

**Comment by LFedorov** [comment]
деструктуризация - вполне устоявшееся понятие

**Comment by another-guy** [comment]
@LFedorov значит в словарь нет смысла добавлять, так?

**Comment by LFedorov** [comment]
можно добавить, на случай возникновения сомнений в дальнейшем
