### ISSUE TITLE
Терминология: persistent

### ISSUE THREAD

**Issue by LFedorov** [reactjs/ru.reactjs.org#142]
Думаю, стоит решить как переводить и занести в словарь.

**Comment by another-guy** [comment]
_устойчиый_? 🤷‍♂️

**Comment by LFedorov** [comment]
> It provides immutable, persistent collections that work via structural sharing
 
иммутабельные, устойчивые коллекции? возникает вопрос - устойчивые к чему?

**Comment by lex111** [comment]
> вообще, я встречал в переводах "персистентность"

:+1: (_хранение_ ещё есть)

https://medium.com/devschacht/sebasti%C3%A1n-peyrott-introduction-to-immutablejs-and-functional-programming-concepts-b3a6555af0ee

**Comment by another-guy** [comment]
> (_хранение_ ещё есть)

Во-первых, тут не совсем согласен.

_persistent **storage**_ это постоянное хранилище. Если бы _persistent_ переводилось точно как _хранилище_, то это было бы масло масляное. Да, в разговорном бывает говорят _persistent_, подразумевая _хранилище_, но это неверно.

---

Во-вторых, предлагаю всегда приводить хотя бы один пример использования обсуждаемого термина. В #141 текст такой:

> *Persistent*: new collections can be created from a previous collection and a mutation such as set. The original collection is still valid after the new collection is created.

То есть речь о [persistent data structure](https://en.wikipedia.org/wiki/Persistent_data_structure).

* [Prompt](https://www.translate.ru/dictionary/en-ru/persistent%20data%20structure/) говорит _персистентная структура данных_.
* [dic.academic.ru](https://translate.academic.ru/persistent%20data/en/ru/) -- _постоянные данные_.
* [Google Translate](https://translate.google.com/#view=home&op=translate&sl=en&tl=ru&text=persistent%20data%20structure): _постоянная структура данных_.

**Comment by lex111** [comment]
Так что, _персистентность_ тогда?

**Comment by another-guy** [comment]
Видимо, так.

**Comment by lex111** [comment]
Кстати на будущее: можно в тексте PR писать что-то вроде "Closes #142", тогда это ишью автоматически закроется.

**Comment by another-guy** [comment]
@lex111 Да. Но с этим надо осторожно. У нас были ишью, в которых обсуждались 2-3 термина сразу...
