### ISSUE TITLE
Терминология: Contibuting

### ISSUE THREAD

**Issue by Heegiiny** [reactjs/ru.reactjs.org#154]
Выражения из **Codebase Overview**, но встречаются и в других главах из **CONTRIBUTING**.

~Codebase - код (не могу придумать, как вставить сюда base, чтобы не получилось длинное словосочетание);~
(to) contribute - участвовать в разработке (_внести вклад_ еще переводят, но мне больше первый вариант нравится, к тому же это в документации, а не в меню).

**Comment by Heegiiny** [comment]
guide - руководство или гайд? Гайд, на мой, взляд, достаточно устоявшеся слово.

**Comment by Heegiiny** [comment]
utilities - утилиты или вспомогательные функции?

**Comment by another-guy** [comment]
@Heegiiny давайте сделаем по issue на термин, чтобы обсуждение было максимально ясным https://github.com/reactjs/ru.reactjs.org/issues/155

**Comment by another-guy** [comment]
_Codebase_:

_кодовая база_ и _база кода_? Например, _в вашей базе кода..._ Или _обзор кодовой базы_

**Comment by Heegiiny** [comment]
Хорошо.

**Comment by another-guy** [comment]
@Heegiiny 

_contribute_:

_содействие [в разработке]_
_делать вклад_

**Comment by lex111** [comment]
Сам раздел мы перевели как _Участие в проекте_, для перевода главы _How to Contribute_ я бы предпочтёл использовать более общий перевод - _Как внести свой вклад_ (поскольку много встречается в рунете) или _Как поучаствовать_ (но не нравится из-за некоторого повтора названия главы), а уже в самом тексте можно использовать _участвовать в разработке_ (например [здесь](https://reactjs.org/docs/how-to-contribute.html#introductory-video) уместнее).
