### ISSUE TITLE
Терминология: utilities

### ISSUE THREAD

**Issue by another-guy** [reactjs/ru.reactjs.org#155]
> utilities - утилиты или вспомогательные функции?

https://github.com/reactjs/ru.reactjs.org/issues/154#issuecomment-464374176

**Comment by another-guy** [comment]
@Heegiiny мне больше нравится простое _вспомогательные функции_. Под _утилитами_ в русском языке чаще понимаются _вспомогательные **приложения**_.

**Comment by Heegiiny** [comment]
Да, согласен, что обычно имеются ввиду приложения.

**Comment by lex111** [comment]
Если использовать _вспомогательные функции_, то получается двойное значение, поскольку _helper_ аналогично переводится.

Но учитывая, что это слово используется пока в контексте тестирования - [Test Utilities](https://reactjs.org/docs/test-utils.html) - и там идёт речь про маленькую библиотеку [ReactTestUtils](https://github.com/facebook/react/blob/master/packages/react-dom/src/test-utils/ReactTestUtils.js), то _вспомогательные функции_ оказываются наиболее подходящим кандидатом для перевода, поскольку под ими подразумеваются utility functions, но тогда получается длинным заголовок - _Вспомогательные функции тестирования_...

А что, если в качестве заголовка будет просто название - ReactTestUtils:

![image](https://user-images.githubusercontent.com/4408379/52905496-f2dcbf80-324b-11e9-9556-cc9284812e67.png)

Пойдём на такую вольность для краткости? Мне кажется, так даже лучше, учитывая что это справочник... :thinking:

**Comment by Heegiiny** [comment]
Мне _utilities_ встретился в

> The [fbjs repository](https://github.com/facebook/fbjs) exists because React shares some small utilities with libraries like [Relay](https://github.com/facebook/relay), and we keep them in sync. We don't depend on equivalent small modules in the Node ecosystem because we want Facebook engineers to be able to make changes to them whenever necessary. None of the utilities inside fbjs are considered to be public API, and they are only intended for use by Facebook projects such as React.

**Comment by another-guy** [comment]
@Heegiiny @lex111 конкретно в случае с заголовком, я думаю, можно сделать исключение и написать `ReactTestUtils`. Но по тексту понятие надо переводить (кроме названия самой библиотеки).
