### ISSUE TITLE
Терминология: guide

### ISSUE THREAD

**Issue by another-guy** [reactjs/ru.reactjs.org#156]
> guide - руководство или гайд? Гайд, на мой взгляд, достаточно устоявшееся слово. https://github.com/reactjs/ru.reactjs.org/issues/154#issuecomment-464370726

**Comment by another-guy** [comment]
@Heegiiny _руководство_ намного более известное слово в русском, не несущее никаких проблем с собой.
"Гайд" это _плохая_ калька, в отличие от многих вынужденных транслитераций, для которых нет уместного перевода.

**Comment by lex111** [comment]
> "Гайд" это _плохая_ калька, в отличие от многих вынужденных транслитераций, для которых нет уместного перевода.

:+1:

**Comment by another-guy** [comment]
В словарях -- _руководство_, поэтому закрываю issue.
