### ISSUE TITLE
Терминология: Codebase

### ISSUE THREAD

**Issue by another-guy** [reactjs/ru.reactjs.org#157]
> Codebase - код (не могу придумать, как вставить сюда base, чтобы не получилось длинное словосочетание);

https://github.com/reactjs/ru.reactjs.org/issues/154

**Comment by another-guy** [comment]
@Heegiiny 

_Codebase_:

_кодовая база_ и _база кода_? Например, _в вашей базе кода..._ Или _обзор кодовой базы_

**Comment by Heegiiny** [comment]
Кодовая база не очень нравится, не встречал ранее в русскоязычных источниках такого словосочетания. Может тогда _обзор исходного кода_? Мне кажется, _исходный код_ используется в подобном значении.

**Comment by another-guy** [comment]
@Heegiiny да, _исходный код_ допустимо использовать в этом значении. Я нейтрален к такому переводу _code base_. И, пожалуй соглашусь с тем, что _кодовая база_ в русской литературе редкость. 

Может ещё у кого-то есть соображения?

**Comment by lex111** [comment]
Да ну, в рунете _кодовая база_ уже [давно](https://www.google.com/search?newwindow=1&biw=1853&bih=927&ei=3XhoXObhB_aFk74PqZadwAQ&q=%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2%D0%B0%D1%8F+%D0%B1%D0%B0%D0%B7%D0%B0+%D1%85%D0%B0%D0%B1%D1%80&oq=%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2%D0%B0%D1%8F+%D0%B1%D0%B0%D0%B7%D0%B0+%D1%85%D0%B0%D0%B1%D1%80&gs_l=psy-ab.3...598.1286..1557...0.0..0.164.678.0j5......0....1..gws-wiz.......0i22i30j33i160j33i21.f1rSjhjg9eQ) в [ходу](https://www.google.com/search?q=%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2%D0%B0%D1%8F+%D0%B1%D0%B0%D0%B7%D0%B0&oq=%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2%D0%B0%D1%8F+%D0%B1%D0%B0%D0%B7%D0%B0&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8) (в книгах кстати тоже [оно](https://www.google.com/search?newwindow=1&biw=1853&bih=927&tbm=bks&ei=p3hoXJuQNszW6AS1u5u4Bg&q=%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2%D0%B0%D1%8F+%D0%B1%D0%B0%D0%B7%D0%B0&oq=%D0%BA%D0%BE%D0%B4%D0%BE%D0%B2%D0%B0%D1%8F+%D0%B1%D0%B0%D0%B7%D0%B0&gs_l=psy-ab.3...12844.14181.0.14760.12.12.0.0.0.0.172.1063.2j7.9.0....0...1c.1.64.psy-ab..3.2.277...0.0.NZTG_elBToQ) встречается).

**Comment by Heegiiny** [comment]
Я бы оставил _исходный код_, так как-то привычнее.

**Comment by another-guy** [comment]
Учитывая, что _кодовая база_ есть в википедии и даже в книгах, я теперь склоняюсь, что именно этот вариант лучше.

Он ближе к исходному тексту. Он менее абстрактен в сравнением с _исходным кодом_ (под которым понимают любой код, даже сниппет, который ещё не скомпилирован в байт-код или машинный код).

**Comment by lex111** [comment]
Может тогда не стоит добавлять его в словарь, если слово специфичное? У нас есть ишью, где обсуждается вопросы по переводу, это как раз тот случай.

**Comment by another-guy** [comment]
Согласен, что можно не заносить в словарь. Фраза есть лишь в двух документах.
