### ISSUE TITLE
> effectively

### ISSUE THREAD

**Issue by Azat74** [reactjs/ru.reactjs.org#168]
> effectively
> трудозатратно

Разве не наоборот?

_Originally posted by @lex111 in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjA0OTk0MzY0/pull_request_reviews/more_threads_

**Comment by Azat74** [comment]
На сколько я понимаю в данном контексте понимается именно то что были потрачены ресурсы на это, несколько раз думал об этом, прошу это прокомментировать.

**Comment by another-guy** [comment]
@Azat74 уточните ссылку, пожалуйста, чтобы увидеть контекст.

**Comment by lex111** [comment]
Это относится к https://github.com/reactjs/ru.reactjs.org/pull/163#discussion_r257870657

Я ответил - https://github.com/reactjs/ru.reactjs.org/pull/163#discussion_r

**Comment by another-guy** [comment]
Раз обсуждение уже идёт в PR, и оно не касается введения термина в словарь, issue следует закрыть.
