### ISSUE TITLE
Incorrect display of non-latin characters

### ISSUE THREAD

**Issue by gcor** [reactjs/ru.reactjs.org#180]
https://ru.reactjs.org/

<img width="606" alt="screen shot 2019-02-22 at 12 35 12 pm" src="https://user-images.githubusercontent.com/4715396/53233458-870cb380-369e-11e9-8269-7e77e3460a74.png">
<img width="589" alt="screen shot 2019-02-22 at 12 35 19 pm" src="https://user-images.githubusercontent.com/4715396/53233459-870cb380-369e-11e9-9c23-312838ca46da.png">

**Comment by another-guy** [comment]
Проблема не специфична для русского. Ниже такая же беда, например, в армянском переводе. Мне кажется, надо эскалировать проблему. Я напишу в Slack, пожалуй


![image](https://user-images.githubusercontent.com/5762340/53234288-1042cc80-3644-11e9-8f81-60f2c15a896d.png)

**Comment by another-guy** [comment]
Написал: https://react-translations.slack.com/archives/CG3V64V0C/p1550829280043700

**Comment by another-guy** [comment]
@gcor Good catch.

**Comment by another-guy** [comment]
Открыл баг в родительском репозитории по совету @tesseralis
