### ISSUE TITLE
Try it on Codepen

### ISSUE THREAD

**Issue by gaearon** [reactjs/ru.reactjs.org#24]
Будем переводить текст этой ссылки?

**Comment by lex111** [comment]
Конечно, почему нет?

**Comment by gaearon** [comment]
Тогда надо определиться сразу, чтобы не было 10 разных вариантов )

**Comment by lex111** [comment]
- `Попробовать на Codepen`
- `Посмотреть на Codepen`

**Comment by ModPhoenix** [comment]
"Запустить на Codepen"?

**Comment by lex111** [comment]
Погуглил, больше всего используется вариант `Посмотреть на Codepen`.

> "Запустить на Codepen"?

Фактически он уже запущен, поэтому это не совсем верно + меньше всего используется, если поискать в гугле.

**Comment by gaearon** [comment]
Посмотреть 👍
