### ISSUE TITLE
Опечатка на странице https://ru.react.js.org/docs/lists-and-keys.html

### ISSUE THREAD

**Issue by Adler991** [reactjs/ru.reactjs.org#243]
Присутствует английская буква "W" непосредственно перед словом "Мы"
![Screenshot_1](https://user-images.githubusercontent.com/35759037/54090489-61a9c600-437d-11e9-9f71-889772fd9500.png)

**Comment by ntishkevich** [comment]
Спасибо за вашу бдительность, но вы ссылаетесь на сайт https://ru.react.js.org/ с неофициальным переводом (вроде бы @lex111 участник того репозитория), а в этом репозитории находится официальный перевод документации по адресу https:/ru.reactjs.org. В этом же разделе документации , в котором обнаружили ошибку, на https://ru.reactjs.org/docs/lists-and-keys.html нету лишних букв.

**Comment by lex111** [comment]
Да, всё верно пишет @ntishkevich, более того, на этом сайте в самом верху есть соответствующая фиолетовая плашка, видимо вы перешли по второй ссылке (кстати, поставьте звёздочку этому репозиторию, нам будет приятно :smile: ) и решили, что это репозиторий сайта с неофициальным переводом. Читайте официальный перевод, тем более он почти уже готов. Но всё равно спасибо за уведомление, закрываю тикет.

**Comment by Adler991** [comment]
Спасибо, извините что зря побеспокоил. В будущем буду повнимательней.
