### ISSUE TITLE
UI bug with text on phones

### ISSUE THREAD

**Issue by gcor** [reactjs/ru.reactjs.org#253]
<img width="320" alt="Screen Shot 2019-03-13 at 6 21 32 PM" src="https://user-images.githubusercontent.com/4715396/54291065-13830580-45bd-11e9-92e0-0270855cb0d3.png">

**Comment by avevlad** [comment]
Текстом поправить наверно не получится, только стилями:

![image](https://user-images.githubusercontent.com/2889662/54295560-55637a00-45c4-11e9-8957-b7611622d883.png)

Могу заняться этим.

**Comment by another-guy** [comment]
@gcor эта проблема специфична для 🇷🇺  версии сайта? Если нет, то лучше решать её на уровне reactjs.org. 🤔 

Я не силён в CSS, так что точно не смогу помочь. И да, я согласен, что надо проблему решать стилями надо.

**Comment by AlLevykin** [comment]
src\pages\index.js
line 316
50% заменить на 100%

**Comment by avevlad** [comment]
@AlLevykin отличное решение!

Работает и на других языках тоже:
<details><summary>картинка</summary><p>

![image](https://user-images.githubusercontent.com/2889662/54374967-3aab0700-4691-11e9-8497-a3d3b3cc0cdf.png)

</p></details>

<br>

Отправишь PR в https://github.com/reactjs/reactjs.org ?

**Comment by another-guy** [comment]
@avevlad есть время и желание открыть PR в родительский проект?

**Comment by avevlad** [comment]
@another-guy да, на днях займусь. Но issue оказалась чуть сложнее чем я думал, по поим тестам  решение:

```
src\pages\index.js -> line 316 50% -> заменить на 100%
```

не очень корректно работает на некоторых разрешениях в en версии, нам и другим языкам оно помогает, а оригинальная версия выглядит хуже. Пока предлагаю поправить этим вариантом у нас, а как найду решение для всех разрешения и языков, создам PR в родительский проект.

**Comment by another-guy** [comment]
@avevlad понял. В любом случае, у нас тут этот issue не должен "висеть", имхо

**Comment by StepanNaryshkov** [comment]
Если что, этот баг на всех языках, если много текста, надо фиксить с расчетом на то, что текст может и вместить и нет

**Comment by lex111** [comment]
Исправлено в #306
