### ISSUE TITLE
Перевод README 

### ISSUE THREAD

**Issue by vvscode** [reactjs/ru.reactjs.org#267]
Будем переводить?

**Comment by another-guy** [comment]
Лично я не против, поскольку общий материал уже переведён.

На будущее: давайте, открывая ишью, предоставлять хоть какой-то контекст и мотивацию. Лично мне кажется, что пользы от этого изменения не так много, но я могу заблуждаться.

**Comment by another-guy** [comment]
@vvscode вы решили, будете ли переводить README? Раз возражений не слышно, этим можно заняться.
