### ISSUE TITLE
possible translation mistakes

### ISSUE THREAD

**Issue by SurenAt93** [reactjs/ru.reactjs.org#280]
Ребята всем привет. Я перевожу React на армянский. Сегодня во время перевода очередной статьи, я наткнулся на одно "нестандартное" предложение. Хотел узнать как вы его перевели, посмотрел ваш вариант, и он по-моему не очень правильный. Речь об этой ([RUS](https://ru.reactjs.org/docs/state-and-lifecycle.html)/[ENG](https://reactjs.org/docs/state-and-lifecycle.html)) статье, и про это предложение:

* ENG - `We will later add the timer code back to the component itself`
* RUS - `Позже мы вернём код таймера обратно в компонент`

Попробую объяснить: в оригинале имеется ввиду, что был код таймера,

```javascript
function tick() {
  const element = (
    <div>
      <h1>Привет, мир!</h1>
      <h2>Сейчас {new Date().toLocaleTimeString()}.</h2>
    </div>
  );
  ReactDOM.render(
    element,
    document.getElementById('root')
  );
}

setInterval(tick, 1000); // <-------------- ВОТ ОНО
```

мы удалили его после кaких-то изменений.

```javascript
class Clock extends React.Component {
  constructor(props) {
    super(props);
    this.state = {date: new Date()};
  }

  render() {
    return (
      <div>
        <h1>Hello, world!</h1>
        <h2>It is {this.state.date.toLocaleTimeString()}.</h2>
      </div>
    );
  }
}

ReactDOM.render(
  <Clock />,
  document.getElementById('root')
);

// ЕГО БОЛЬШЕ НЕТ :(
```

Потом мы вернем его обратно, но в этот раз поместим это в компонент.

```javascript
class Clock extends React.Component {
  constructor(props) {
    super(props);
    this.state = {date: new Date()};
  }

  componentDidMount() {
    this.timerID = setInterval( // <-------------- ВОТ ОНО
      () => this.tick(),
      1000
    );
  }

  ...
```

Вы написали **"Позже мы вернём код таймера обратно в компонент"**. Так, хочу сказать что не **"обратно в компонент"**, он в компоненте и не был. Касательно **"обратного"** автор имеет ввиду **"вернём обратно"**, но не **"обратно в компонент"**.

Мой вариант, который я 
написал в армянском переводе, на русском будет как-то так: **"Позже мы вернём код таймера обратно и положим в компонент"** или можно еще так **"Позже мы вернём код таймера обратно: на этот раз в сам компонент"**.

**Comment by ntishkevich** [comment]
Дельно замечание, спасибо 👍 💪! Мне нравится первый предложенный вариант. А как думаете, если заменим слово «положим» на «поместим» станет ли лучше?

**Comment by SurenAt93** [comment]
Для меня, интуитивно, более подходящий вариант - это «поместим». Но, интуитивно... Я воздержусь сказать что-то по этому поводу, потому что могу не понять некоторые тонкости русского языка (я не носитель языка), можем подождать других мнений.

И я наткнулся на еще одно предложение, которое можно улучшить, я немного позже напишу здесь, пока еще не закройте пожалуйста этот issue.

**Comment by SurenAt93** [comment]
Так, в оригинале есть такой кусок из двух предложений:

```text
Finally, we will implement a method called tick() that the Clock component will run every second.


It will use this.setState() to schedule updates to the component local state:
```

Вы это перевели как:

```text
Наконец, реализуем метод tick(). Он запускается таймером каждую секунду и вызывает this.setState().


this.setState() планирует обновление внутреннего состояния компонента:
```

Во первых, по моему, в переводе первого предложения слова автора немного искажены (мы например уделяем большое внимание на слова/структуру оригинала/автора). Во вторых, по моему, перевод второй части не правильный:

`this.setState() планирует обновление внутреннего состояния компонента:`

Tак, я думаю что `this.setState()` ничего не планирует. В оригинале написано

`It will use this.setState() to schedule updates to the component local state:`

**It** имеется в виду `tick()`, который будет использовать `this.setState()`, для планирование обновление внутреннего состояния компонента.

**Comment by another-guy** [comment]
@SurenAt93 вы всё правильно говорите! Спасибо огромное за замечания! Поправим эти места.

**Comment by SurenAt93** [comment]
@ntishkevich, @another-guy You are welcome guys! Если я наткнусь на что-то еще, напишу здесь.

**Comment by another-guy** [comment]
@SurenAt93 непременно пишите. И, если есть время, открывайте pullrequest, это ускорит процесс. Мы особенно доверяем и внимательны к замечаниям переводчиков на другие языки.
