### ISSUE TITLE
Терминология:  populate = заполнить?

### ISSUE THREAD

**Issue by avevlad** [reactjs/ru.reactjs.org#33]
> populate local state

- Заполнить внутреннее состояние?
- Задать внутреннее состояние?
- Обновить внутреннее состояние?

Просто "Заполнить внутреннее состояние" звучит как то странно.

**Comment by gaearon** [comment]
Не знаю, мне заполнить звучит норм и вроде по смыслу. Речь именно о том, чтобы его заполнить из AJAX-ответа, а не об общем обновлении или задании.

**Comment by another-guy** [comment]
"Заполнить", и правда, немного режет слух.

По жизни я только встречал "присвоить", "записать", "обновить", "задать". Реже: "применить (состояние). Но я не уверен, что хоть один из вариантов хорошо передаёт смысл. ¯\_(ツ)_/¯

**Comment by gaearon** [comment]
В общем-то мне не принципиально )

**Comment by avevlad** [comment]
В доке кроме faq почти не встречается. Пусть пока будет будет *Заполнить*, хотя и варианты @another-guy мне симпатичны.
