### ISSUE TITLE
Плагины Gatsby (кавычки-ёлочки и проч.)

### ISSUE THREAD

**Issue by gaearon** [reactjs/ru.reactjs.org#35]
У нас включен плагин Gatsby, который автоматически конвертирует "" в “” и - в — где надо. Но он не знает про кириллицу и не в курсе, что надо ставить ёлочки. Надо его научить.

**Comment by lex111** [comment]
А как он называется, не подскажешь? Не могу определить.

**Comment by gaearon** [comment]
https://www.gatsbyjs.org/packages/gatsby-remark-smartypants/

**Comment by ModPhoenix** [comment]
Случайно увидел в разметке если поставить `--` это будет трансформировано в `—`. Правда я не разбирался это фича markdown или это делает плагин Gatsby.

**Comment by everdimension** [comment]
Подскажу, что есть отличная библиотека https://github.com/iamstarkov/typographic-quotes

**Comment by another-guy** [comment]
Кто-нибудь знает, что ответственно за нестинг через синтаксис `embed:<file-ref>` ?
