### ISSUE TITLE
Не переведенная страница Shallow Compare

### ISSUE THREAD

**Issue by Dissarion** [reactjs/ru.reactjs.org#350]
Не уверен, но возможно эта страница была пропущена https://ru.reactjs.org/docs/shallow-compare.html

**Comment by ntishkevich** [comment]
Верно, эта страница была упущена, ее не было в списке страниц к переводу в [задаче](https://github.com/reactjs/ru.reactjs.org/issues/1 ) к обязательному переводу. Не могли бы рассказать где встречалась ссылка или как удалось перейти на указанную вами страницу ?

Мы будем рады вашей помощи в дальнейшем, спасибо.

**Comment by Dissarion** [comment]
Эти ссылки были получены из результатов поисковой выдачи гугла https://imgur.com/a/9FqHzbo

**Comment by gcor** [comment]
Страница переведена.
