### ISSUE TITLE
Перевод страницы Profiler

### ISSUE THREAD

**Issue by ntishkevich** [reactjs/ru.reactjs.org#382]
**Прежде чем переводить, обязательно прочитайте [местные правила перевода](https://github.com/reactjs/ru.reactjs.org/blob/master/TRANSLATION.md)!**

Появилась новая страница в секции с продвинутыми темами
- [ ] [Profiler](https://github.com/reactjs/ru.reactjs.org/blob/master/content/docs/reference-profiler.md) (✏️ @IgorLesnevskiy)

**Comment by IgorLesnevskiy** [comment]
если ей никто не занимается, то возьму в перевод, на выходных сделаю
