### ISSUE TITLE
Перевод страницы Immutability Helpers

### ISSUE THREAD

**Issue by Dissarion** [reactjs/ru.reactjs.org#395]
Нет перевода этой страницы https://ru.reactjs.org/docs/update.html

Найдена эта страница на SO https://stackoverflow.com/a/29537485/10145626

Так же страница гуглится, если делать запрос на русском.

**Comment by lex111** [comment]
> update is a legacy add-on. Use immutability-helper instead.

В общем, особого смысла нет.

**Comment by Dissarion** [comment]
За ненадобностью перевода - закрываю
