### ISSUE TITLE
Терминология: child

### ISSUE THREAD

**Issue by gcor** [reactjs/ru.reactjs.org#40]
child components – дочерние компоненты
child – дочерний компонент
children – дочерние компоненты

child components – чайлд-компоненты
child – чайлд
children – чайлды

Кажется, лучше в любом случае писать длинно.

**Comment by lex111** [comment]
> child components – дочерние компоненты
child – дочерний компонент
children – дочерние компоненты

> Кажется, лучше в любом случае писать длинно.

Однозначно :+1:

**Comment by another-guy** [comment]
В своём переводе я использовал "дочерний компонент" и производные. В каком-то PR я видел другой вариант. Интересно, как будем осуществлять вычитку на согласованность терминов во всех главах.

P.S. Чайлд-компоненты я нигде не видел на письме раньше.
