### ISSUE TITLE
Терминология: tutorial = учебник?

### ISSUE THREAD

**Issue by avevlad** [reactjs/ru.reactjs.org#41]
@AlLevykin в PR #39 перевел *in the tutorial* как *в практическом руководстве*

Давайте обсудим, tutorial это:

- учебник
- книга
- руководство
- практическое руководство

**Comment by AlLevykin** [comment]
- обучающий пример
- обучающее пособие

**Comment by lex111** [comment]
Я за "руководство", как самый короткий, поскольку этот пункт будет отображаться в верхнем меню

**Comment by AlLevykin** [comment]
Необходимо обозначить различие между "Practical Tutorial" и "Step-by-Step Guide" (guide to main concepts).

**Comment by lex111** [comment]
Хм, тогда может оставить "учебник", хоть он и _простой_, а Step-by-Step Guide это то же самое что и tutorial.

**Comment by gaearon** [comment]
Учебник у меня как раз вызывает теоретические ассоциации. А это скорее практический walkthrough.

**Comment by gaearon** [comment]
Введение?

**Comment by lex111** [comment]
Отлично, по-моему!

**Comment by gaearon** [comment]
Он даже на странице называется "Tutorial: Intro to React" так что вроде всё правильно. )

**Comment by lex111** [comment]
:man_facepalming:

**Comment by avevlad** [comment]
ок, создать PR в TRANSLATION.md?

**Comment by gaearon** [comment]
sure

**Comment by gaearon** [comment]
Еще может быть "тур" но так про текст не говорят?

**Comment by gaearon** [comment]
Или "обзор"

**Comment by gaearon** [comment]
или курс...

**Comment by avevlad** [comment]
А давайте плиз решим тут как переведем:

> Learn what React is all about on our homepage or in the tutorial.

так? 

> Узнать все о React можно в ведении или на домашней странице.

**Comment by lex111** [comment]
Введение — лучше всего :1st_place_medal:

**Comment by lex111** [comment]
> домашней странице

главная страница?

**Comment by gaearon** [comment]
Еще надо Docs в заголовке коротко как-то.

**Comment by avevlad** [comment]
@gaearon Доки!

**Comment by lex111** [comment]
Документация, аналогично как сейчас https://ru.react.js.org/

**Comment by gaearon** [comment]
На мобильном даже английская версия плохо вмещается. Было бы лучше если бы можно без скролла.

<img width="391" alt="screen shot 2019-02-09 at 11 51 36 pm" src="https://user-images.githubusercontent.com/810438/52527744-a7fbfe80-2cc5-11e9-8b73-8f623c281210.png">

**Comment by lex111** [comment]
Ну, такое.. я про "доки".
+ как показывает твой пример, то на русском будет не лучше, нужно идти на компромиссы.

**Comment by gaearon** [comment]
Соглашусь пожалуй.

**Comment by avevlad** [comment]
Согласен что "доки так себе", но общаюсь я между колегами так.

Как вариант конечно оставить Docs.

**Comment by gaearon** [comment]
Документация ок, просто шапка будет раньше скроллиться. Ничего.

Думаю, придется переменовать Введение в JSX чтобы не создавать путаницы с главным Введением.

**Comment by avevlad** [comment]
Когда весь остальной сайт будет переведен, **Docs** на латинице не будет сильно выделяться.

**Comment by lex111** [comment]
> Думаю, придется переменовать Введение в JSX чтобы не создавать путаницы с главным Введением.

https://reactjs.org/docs/introducing-jsx.html - Введение в JSX
https://reactjs.org/tutorial/tutorial.html - просто "Введение"

Правильно?

**Comment by gaearon** [comment]
Да, но всё равно мне кажется можно заблудиться или подумать, что уже видел "введение", прочитав про JSX.

**Comment by gaearon** [comment]
Можно буквально перевести introducing — "знакомство", тогда не будет пересекаться.

**Comment by lex111** [comment]
> Можно буквально перевести introducing — "знакомство", тогда не будет пересекаться.

Кстати, да!

**Comment by gaearon** [comment]
ok, я сделал https://github.com/reactjs/ru.reactjs.org/pull/43

**Comment by avevlad** [comment]
Сделаю PR для правки TRANSLATION.md

**Comment by vvscode** [comment]
Перечитал топик и не понял - почему `Введение`? откуда?

**Comment by vvscode** [comment]
ну и например такие фразы `We strongly recommend typing code by hand as you're working through the tutorial and not using copy/paste.` - какой вариант перевода?

**Comment by gcor** [comment]
Если говорить про раздел Tutorial, то мне нравится перевод _Введение_, потому что он отражает то, что это не полное руководство или учебник, это именно основы для новичков.

Можно перевести так: «Код из этого введения мы рекомендуем писать самостоятельно, а не просто копировать»

Но в некоторых местах всегда можно употребить руководство, если оно точнее передаст смысл.

**Comment by vvscode** [comment]
`из этого введения` - мне режет слух

Плюс заголовок `Tutorial: Intro to React` - он как бы отражает, что `tutorial` не про введение, про него `Intro`

**Comment by gcor** [comment]
`из этого раздела` можно

Слово руководство по мне это что-то полное и скорее антоним к введению. Получится странно, как бы руководство по введению. Здесь подходит перевод учебник или учебное пособие (Учебное пособие: введение в React). Но, как выше обсуждали, это скорее получится что-то про теорию, а тут практика.

Я за вариант _Введение: знакомство с React_ или просто _Введение_

**Comment by lex111** [comment]
> Введение: знакомство с React 

Для заголовка отлично подходит.

**Comment by vvscode** [comment]
> Руководство пользователя — документ, назначение которого — предоставить людям помощь в использовании некоторой системы.

> 3. Учебник, пособие для изучения чего-нибудь
@gcor 
про `полное`  это откуда? у меня вот такой ассоциасии нет

**Comment by gcor** [comment]
Руководство у меня ассоциируется с чем-то сложным. Например, руководство по эксплуатации холодильника или руководство по работе со стиральной машиной. И это выглядит, как крупная книжка. Но может это только у меня 😄

**Comment by vvscode** [comment]
Ну видимо не только я не согласен с таким подходом )
https://www.ozon.ru/context/detail/id/5578850/
https://www.ozon.ru/context/detail/id/142419474/
https://www.ozon.ru/context/detail/id/5993100/

**Comment by lex111** [comment]
Ну и книжки ты привёл в качестве примера 🤣🤣🤣
