### ISSUE TITLE
Терминология: concurrent mode

### ISSUE THREAD

**Issue by gcor** [reactjs/ru.reactjs.org#423]
Варианты:
– Параллельный режим
– Конкурирующий режим
– Конкурентный режим
– Одновременный режим

Первый вариант переводят все популярные переводчики. Плюс в википедии есть статья про параллельные вычисления (Concurrent computing).

**Comment by gaearon** [comment]
Параллельный близко по смыслу, но вносит путаницу с полным параллелизмом. Который может быть когда-нибудь и появится в будущем.

**Comment by gaearon** [comment]
Вброшу еще пару вариантов:

- Совместный режим
- Согласованный режим
- Одновременный режим
- Многозадачный режим

**Comment by gorkunov** [comment]
**Конкурентный режим**  будет самое понятное, т.к. очень близко к оригиналу и не теряет сути.

**Comment by andreypopp** [comment]
* Многопоточный режим (но есть может возникнуть путаница преемптивной многопоточностью)
* Мультипоточный режим (звучит как новоизобретённый термин)

На мой взгляд, у термина Конкурентный Режим есть очень большое преимущество в созвучии с оригинальным Concurrent Mode. Читателям документации все же полезно знать оригинальные термины, так как за пределами ru.reactjs.org информация по теме будем в основном на английском языке.

**Comment by gaearon** [comment]
В интернетах я тоже в основном нахожу «конкурентный» когда идет обсуждение concurrent vs parallel. Конкурентный ок. Не идеально, но наверное лучший вариант из тех, что есть.

**Comment by sergeypedan** [comment]
Собегущий режим

**Comment by nick-rudenko** [comment]
**Конкурентный режим** - безусловно, наиболее подходящий вариант, но само слово "конкурентный" вводит в заблуждение. Думаю в документации стоит сделать небольшую сноску с растолкованием этого слова.

**Comment by gaearon** [comment]
Лично мне больше всех нравится Совместный режим.

**Comment by gaearon** [comment]
Главная фича — это то, что пока выполняется один setState, можно сделать другой. То есть они выполняются совместно (и впоследствии мёржатся). Рантайм модель по сути это совместная (кооперативная) многозадачность.

**Comment by gaearon** [comment]
Хотя Concurrrent Mode и Совместный Режим не прямой перевод, они хотя бы визуально похожи по первым буквам и их количеству. Так что какая-то связь остется.

**Comment by gaearon** [comment]
Есть еще такая штука. Если русский термин длиннее английского, люди в разговоре все равно начнут использовать английский. Просто потому что короче. Так что хотелось бы не больше трех слогов для перевода concurrent.

**Comment by ivansvlv** [comment]
> В интернетах я тоже в основном нахожу «конкурентный» когда идет обсуждение concurrent vs parallel. Конкурентный ок. Не идеально, но наверное лучший вариант из тех, что есть.

Не согласен, как по мне в переводе утерян смысл. **Согласованный режим** в моем понимании звучит наиболее понятней. Аргументация ниже.

Wikipedia:

> concurrent computing consists of process lifetimes overlapping, but execution need not happen at the same instant.

> For example, concurrent processes can be executed on one core by interleaving the execution steps of each process via time-sharing slices: only one process runs at a time, and if it does not complete during its time slice, it is paused, another process begins or resumes, and then later the original process is resumed. In this way, multiple processes are part-way through execution at a single instant, but only one process is being executed at that instant.

Процессы не могу выполнятся одновременно, их жизненный цикл проходит в одно время, но в процессе выполнение каждому дается вычислительное время. Поэтому процессы **Согласовывают** время своего выполнения, начало и конец процесса.

Если читать English-English переводы **concurrence**, то смысл передается четче. К примеру:

(Merriam-Webster Dictionary)
a :  agreement or union in action :  combination of power or influence :  cooperation <concurrence in doing good> 
b :  a meeting of minds :  agreement in opinion; also :  consent 

(Merriam-Webster Dictionary)
Копая глубже, синоним слова concurrence - **coexisting** или **coexist** с определением: 
1)
:  to exist together or at the same time <its educational and manufacturing interests coexist without friction — American Guide Series: Michigan>
2)
:  to live in peace with each other especially as a matter of policy — used especially of countries with seemingly incompatible policies 

Так же интересные переводы в Collins для слова **concurrent**:
1) Taking place at the same time or in the same location
2) Cooperating
3) Meeting at, approaching, or having a common point: concurrent lines
4) Having equal authority or jurisdiction
5) In accordance or agreement; harmonious

Читая почти кажды перевод у меня в голове представление, о согласованности, договоре, и кооперации. Как бы процессам нужно **Согласовывать** свои действия для выполнения.

**Comment by adaniliuk** [comment]
Возможно, тогда **Кооперативный режим**? Он ближе всего будет по смыслу к вариантам **Совместный режим** или **Согласованный режим**.

p.s. **Конкурентный режим** - тоже очень ок и созвучно с оригиналом.

**Comment by VeronikaHar** [comment]
Конкурентный режим - самый адекватный перевод и с психологической точки зрения, тк в связи с его созвучностью с concurrent mode, мозг быстрее его впишет в систему и легче будут восприниматься крос-язычные контексты.

**Comment by KrickRay** [comment]
режим совмещения / совмещенный режим

**Comment by Snuux** [comment]
Я тоже за конкурентный режим. А еще можно "режим конкурентности".

**Comment by infodusha** [comment]
Как вариант еще "соревновательный режим"

**Comment by atellmer** [comment]
Google translate говорит, что **con** - "против", а **current** - "текущий". Против текущего) Ну тут по смыслу только "конкурентный" подходит)

**Comment by lex111** [comment]
Вариант "Конкурентный режим" звучит неплохо, как по мне, не так давно в переводе одного поста в блоге именно так перевели. Хотя "Совместный режим" по-моему тоже очень хорошо, но большинство людей, как я вижу, за первый вариант, поэтому лучше остановиться на нём.

cc @reactjs/reactjs-org-russian-translation

**Comment by gaearon** [comment]
👍

**Comment by YChebotaev** [comment]
Может, вытесняющий режим?

Если я все правильно понял, то принцип ровно точно такой же, как и при вытесняющей многозадачности в ОСах. Выделяется квант времени, и если какая-то другая задача более приоритетна, она вставляется между квантами. А потом управление возвращается.
Старая-добрая концепция, всем давно понятная.
