### ISSUE TITLE
Скорректировать шаблон для пулреквеста

### ISSUE THREAD

**Issue by lex111** [reactjs/ru.reactjs.org#44]
Проблема: в новых переводах много "нарушений" [руководства перевода](https://github.com/reactjs/ru.reactjs.org/blob/master/TRANSLATION.md), мне кажется нужно внести корректировки в [шаблон пулреквеста](https://github.com/reactjs/ru.reactjs.org/blob/master/.github/PULL_REQUEST_TEMPLATE.md), добавив чекбокс для отметки, типа так:

- [x] Прочитал руководство по переводу

**Comment by gaearon** [comment]
Я пока сделал так https://github.com/reactjs/ru.reactjs.org/commit/ea1c99208ab602fc1ca130d2651a235fff3834d6

**Comment by lex111** [comment]
Отлично, закрываю.
