### ISSUE TITLE
Избыточный перевод кода

### ISSUE THREAD

**Issue by AleksandrZhukov** [reactjs/ru.reactjs.org#491]
В документации помимо описания так же переведен код, например, здесь переведен текст ошибок. 
https://github.com/reactjs/ru.reactjs.org/blame/2451dcd4e4b26498acd5b7b4f3a582bdb5b48d35/content/docs/typechecking-with-proptypes.md#L113

В переводах на другой язык эта часть остается на английском.

**Comment by gcor** [comment]
Вам кажется это неверным?

Если человек не знает английский, ему будет удобнее разобраться на русском.

**Comment by AleksandrZhukov** [comment]
да, Вы правильно меня поняли
Одно дело документация, но комментарии в коде, вывод ошибок и тд должно быть на едином языке разработки - английском
Согласитесь, если вы попадете на проект к японцам (как пример), а там все комментарии, названия переменных(транслитом) и прочее будет на японском вам будет крайне сложно разобраться в таком коде

**Comment by gcor** [comment]
Цель документации — помочь разобраться. 
Помогать разбираться можно и в теории и в практике = и в тексте и в коде.

Процессы разработки конкретной компании и негласные правила это другое.

**Comment by lex111** [comment]
Тоже не понимаю суть претензии, особенно сравнение с промышленной разработкой, это вообще сугубо индивидуально.

Тем более в общем руководстве по переводам это не запрещено https://github.com/reactjs/reactjs.org-translation/blob/master/style-guide.md#text-in-code-blocks
Поэтому мы стараемся переводить по максимуму всё, что можно.

Ну и кстати, украинцы и поляки тоже перевели эти ошибки. И как мне кажется, имея дело с переводом, так и нужно делать. Каждая команда перевода решает индивидуально, переводить ли содержимое _примеров_ кода.

Да, есть переводы, где ни строки, ни комментарии не переведены, это скорее носит рекомендательный характер. Мы наоборот приложили больше усилий, чтобы на выходе получился полноценный перевод.
