### ISSUE TITLE
There is no link to the next section in the version https://ru.react.js.org/docs/introducing-jsx.html

### ISSUE THREAD

**Issue by Padavan-itbeard** [reactjs/ru.reactjs.org#513]
1) раздел - JSX представляет из себя объекты
В предложении "Мы рассмотрим отрисовку элементов React в DOM в следующем разделе." отсутствует линк на следующий раздел. Как сделано в англо язычной версии - We will explore rendering React elements to the DOM in the next section.

2) раздел - Почему JSX?
В предложении "Мы вернёмся к компонентам в следующем разделе, но если вы ещё не очень хорошо умеет размещать разметку в JS, этот доклад может убедить вас в другом."
умеет - нужно заменить на - умеете

**Comment by gcor** [comment]
@Padavan-itbeard, если у вас есть возможность, вы можете сами создать пул-реквест с правками и мы их примем.

**Comment by Padavan-itbeard** [comment]
Привет, я с удовольствием. Но не нашел репо русской версии, которая лежит на сайте. Поделитесь линком?19.06.2020, 13:16, "Anton Ahatov" <notifications@github.com>:
@Padavan-itbeard, если у вас есть возможность, вы можете сами создать пул-реквест с правками и мы их примем.

**Comment by ntishkevich** [comment]
> Привет, я с удовольствием. Но не нашел репо русской версии, которая лежит на сайте. Поделитесь линком?19.06.2020, 13:16, "Anton Ahatov" <notifications@github.com>: @Padavan-itbeard, если у вас есть возможность, вы можете сами создать пул-реквест с правками и мы их примем. —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

Держите ссылку https://github.com/reactjs/ru.reactjs.org 
Вы в нем создали ишью эту : D

**Comment by Padavan-itbeard** [comment]
Жесть) На Git Hub лежит другой текст)) И где читать? )) Issues можно закрыть, здесь такого фрагмента нет
