### ISSUE TITLE
Сделать настройку для русского перевода, чтобы перекидывало на английский

### ISSUE THREAD

**Issue by YChebotaev** [reactjs/ru.reactjs.org#520]
У меня гугл на русском (я его использую не только для программирования), и когда я хочу что-то найти по реакту, он находит русский перевод.

Мне не привычно и не приятно читать русский перевод, поскольку приходится в уме переводить его обратно на английский, чтобы было понятно о чем именно тут говорится.

Я вообще всю документацию по всему что связанно с программированием читаю только на английском и это для меня понятней и привычней.

Я вижу решение этой задачи в том, чтобы сделать на сайте персональную настройку предпочитаемого перевода, чтобы вне зависимости от того, на какой поддомен перешел читатель по ссылке, открывался именно тот перевод, который он для себя выбрал (внешний редирект на уровне сервера статики. Саму настройку прописывать в куке, соответственно, веб-сервер сможет ее прочитать).
Разумеется, эта логика работает только для тех, кто выбрал себе перевод. Новые пользователи попадают на тот, который для них нашел поисковик.

Сделайте, пожалуйста.

**Comment by ntishkevich** [comment]
Привет. Мы в этом репозитории занимаемся переводом документации. Любые улучшения сайта следует оформлять в issues к репозиториию с официальной английской документацией https://github.com/reactjs/reactjs.org. После реализации там новых фич, они попадут к нам через пулл реквест. Данный ишью закрываю.

**Comment by YChebotaev** [comment]
@ntishkevich Спасибо за подсказку.

**Comment by YChebotaev** [comment]
https://github.com/reactjs/reactjs.org/issues/3187
