### ISSUE TITLE
Код на CodePen

### ISSUE THREAD

**Issue by another-guy** [reactjs/ru.reactjs.org#58]
В issue #24 было решено, как перевести текст ссылки, ведущей на CodePen.

У меня возник вопрос, оставляем ли мы сам код на CodePen как есть (с английскими комментариями) или же клонируем код и исправляем комментарии на русский в точном соответствии с кодом в документации (вряд ли овчинка стоит выделки)?

**Comment by avevlad** [comment]
> вряд ли овчинка стоит выделки

+1

**Comment by lex111** [comment]
Сейчас подумал, поскольку мы переводим (да?) текст в примерах кода, то при в примерах CodePen остаётся оригинальное содержимое, что вызывает несогласованность. Не знаю, критично ли это, поскольку хотелось всё-таки переводить текст в примерах кода, но вместе с этим, в примерах CodePen будет по-прежнему английский...

Или ничего, что будет так?

**Comment by another-guy** [comment]
@lex111 в этом и заключается вопрос, поднятый в этом ишью. @avevlad и я сходимся на том, что несогласованность с примером на CodePen в языке это неприятная шероховатость, но она не должна стать "blocking" для читателя. А отслеживать и поддерживать множество примеров на CodePen в лучшем случае затруднительно.

**Comment by gaearon** [comment]
>Хотелось бы просто "официально" решить, что CodePen примеры -- out of scope. По крайней мере, точно не в v1.

Согласен.
