### ISSUE TITLE
Я не знаток но подозрительно

### ISSUE THREAD

**Issue by pavelkudr** [reactjs/ru.reactjs.org#582]
страница https://ru.reactjs.org/docs/state-and-lifecycle.html
"Обратите внимание, что мы передаём props базовому (родительскому) конструктору:"

Почему то мне кажется мы передаем не родительскому а дочернему
Прошу прощения если я не прав

**Comment by lex111** [comment]
Нет, всё верно, `super(props)` - это как раз вызов конструктора родительского компонента (`React.Component`), которому мы передаём пропсы текущего (дочернего) компонента (`Clock`).
