### ISSUE TITLE
Поправить битую ссылку

### ISSUE THREAD

**Issue by it-efrem** [reactjs/ru.reactjs.org#594]
**На странице**
`https://ru.reactjs.org/docs/events.html`

**В блоке**
`Начиная с 17 версии, вызов e.persist() не имеет смысла, потому что объекты событий SyntheticEvent больше не добавляются в пул.`

По факту ссылка
`https://ru.reactjs.org/docs/legacy-event-%D0%BF%D1%83%D0%BB%D0%B8%D0%BD%D0%B3.html`

Должна быть
`https://ru.reactjs.org/docs/legacy-event-pooling.html`

**Comment by lex111** [comment]
Спасибо, исправлено.
