### ISSUE TITLE
Добавлять в скобках английские термины

### ISSUE THREAD

**Issue by Lehakos** [reactjs/ru.reactjs.org#624]
Мне кажется было бы полезно, когда вводится какой-то новый термин, в скобках указывать оригинал на английском. Например:

> В терминах React компонент Square теперь является **управляемым**

Можно было бы в скобках указать controlled

**Comment by scffs** [comment]
Статьи будут переполнены такими скобками.
Нет сильной необходимости так делать.

**Comment by ntishkevich** [comment]
В некоторых местах, где может возникнуть путаница или для больше ясности, мы используем такой подход, в иных случаях скобки с английским словом не используется. Закрываю данный ишью, ответ был дан.
