### ISSUE TITLE
Терминология: side-effects

### ISSUE THREAD

**Issue by gcor** [reactjs/ru.reactjs.org#63]
side-effects = Побочные эффекты
side-effects = Сайд-эффекты

Кажется, второй вариант лучше. 

В [словаре веб-стандартов](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#client-side) уже есть слово «сайд» (client-side = клиентсайд, server-side = серверсайд)

**Comment by another-guy** [comment]
Не очень понимаю, чем именно второй вариант лучше. Особенно, учитывая что "побочный эффект" это очень понятно по-русски и общеизвестно в контексте программирования ([напр. Википедия](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%B1%D0%BE%D1%87%D0%BD%D1%8B%D0%B9_%D1%8D%D1%84%D1%84%D0%B5%D0%BA%D1%82_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5))). 

Просто наличие части "сайд" в паре других слов мне кажется недостаточно сильной причиной применять эту часть повсеместно. Тем более, что и в client/server-side можно было бы обойтись без них, говоря "на стороне клиента/сервера".

**Comment by gcor** [comment]
Мне показалось, что сайд-эффекты чаще используют в устной форме. В статьях же про реакт часто совсем не переводят и оставляют side-effects.

Сейчас я согласен, что побочные эффекты, всё-таки лучше, потому-что это устоявшийся термин.

Статистика по [поиску хабра](https://habr.com/ru/search/?target_type=comments&order_by=relevance&q=%D0%BF%D0%BE%D0%B1%D0%BE%D1%87%D0%BD%D1%8B%D0%B5+%D1%8D%D1%84%D1%84%D0%B5%D0%BA%D1%82%D1%8B&flow=) для интереса:
Побочные эффекты: публикации (1k), комментарии (1k)
side-effects: публикации (136), комментарии (199)
сайд-эффекты: публикации (129), комментарии (512)

**Comment by lex111** [comment]
Я тоже за _побочные эффекты_, поскольку мы довольно уже много используем варваризмов, и поэтому хотелось бы ограничить их использование, насколько это возможно. И это как раз такой случай.

> В статьях же про реакт часто совсем не переводят и оставляют side-effects.

Вот в этом и вся проблема: многое просто пишется как оригинале, хотя можно написать (воспроизвести) на русский, пусть даже и использовав транслитерацию.
