### ISSUE TITLE
Некорректный код в переводе страницы

### ISSUE THREAD

**Issue by BaranovRoman** [reactjs/ru.reactjs.org#744]
Страница - https://ru.react.js.org/docs/state-and-lifecycle.html#%D0%94%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F-%D0%B2-%D0%BA%D0%BB%D0%B0%D1%81%D1%81

В блоке кода отображается this.props.date вместо this.state.date
В репозитории в документации корректный код, в сгенерированной html странице нет

**Comment by ntishkevich** [comment]
Указанная вами ссылка, ведет не на официальную [русскую документацию React](https://ru.reactjs.org/). Об это даже плашечка на сайте говорит. 
Также сообщу, что в[ официальной русской](https://ru.reactjs.org/docs/state-and-lifecycle.html) нет проблемы этой, можете проверить самостоятельно
Закрываю.
