### ISSUE TITLE
Терминология: helper

### ISSUE THREAD

**Issue by gcor** [reactjs/ru.reactjs.org#75]
В контексте:

_помощник_ мемоизации
_хелпер_ мемоизации
_утилита_ мемоизации
_помощник_ для мемоизации
_хелпер_ для мемоизации
_утилита_ для мемоизации

**Comment by lex111** [comment]
> _помощник_ мемоизации
_хелпер_ мемоизации

Я между этими вариантами...

**Comment by another-guy** [comment]
Есть ещё "вспомогательный класс" или "вспомогательная функция". Так часто пишут. "Вспомогательный", правда, сложно применить вместе с мемоизацией. Но в устной речи -- "хелпер" встречается сплошь и рядом.

Настолько много калек/заимствований, что я иногда спрашиваю себя, а переводили ли мы что-то вообще в документе?

**Comment by gaearon** [comment]
В конкретном примере можно просто "мемоизирующая функция"

**Comment by lex111** [comment]
> Есть ещё "вспомогательный класс" или "вспомогательная функция". Так часто пишут.

Кстати, да, и этот вариант даже больше по-моему используется при переводе.

https://reactjs.org/docs/react-api.html#createfactory

**Comment by gaearon** [comment]
Вспомогательный ок
