### ISSUE TITLE
"Измерять раскладку" звучит странно

### ISSUE THREAD

**Issue by manInit** [reactjs/ru.reactjs.org#786]
На странице [использование хуков](https://ru.reactjs.org/docs/hooks-effect.html#:~:text=%D1%8D%D1%82%D0%BE%20%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C%20(%D0%BD%D0%B0%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%2C-,%D0%B8%D0%B7%D0%BC%D0%B5%D1%80%D1%8F%D1%82%D1%8C%20%D1%80%D0%B0%D1%81%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D1%83,-)%2C%20%D0%BD%D0%BE%C2%A0%D0%B4%D0%BB%D1%8F%20%D1%8D%D1%82%D0%BE%D0%B3%D0%BE) текст "measuring layout" переведен как измерение раскладки. Хотя явно имеется ввиду, про измерение размеров DOM элементов. 

Предлагаю варианты по типу "Измерения размеров макета" / "Измерения размеров страницы" / "Измерение элементов"
Даже не знаю что лучше еще подобрать. Но "раскладка" кажется явно не вписывается сюда

**Comment by scffs** [comment]
Изменил на "например, измерять размеры элементов на странице", будем ждать рассмотрения
