### ISSUE TITLE
Как работает функция в React?

### ISSUE THREAD

**Issue by Maxim041411** [reactjs/ru.reactjs.org#804]
Не могу разобраться разобраться как работает функция "handleClick" в данном коде. Подскажите, какие операции происходят в теле функции и как они связаны с другими компонентами? 

import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';

class Square extends React.Component {
    
  render() {
     
        return (
        <button className="square"
        onClick={() => this.props.onClick()}>
          {this.props.value}
        </button>
      );
    }
  }
  
  class Board extends React.Component {
    constructor(props) {
    super(props);
    this.state = {
        squares: Array(9).fill(null)
    };
}
handleClick (i) {
  const squares = this.state.squares.slice();
  squares[i] = 'X';
  this.setState({squares : squares})
}
    renderSquare(i) {
      return <Square value = {this.state.squares[i]}
        onClick = {() => this.handleClick(i)}
      />;
    }
  
    render() {
      const status = 'Next player: X';
  
      return (
        <div>
          <div className="status">{status}</div>
          <div className="board-row">
            {this.renderSquare(0)}
            {this.renderSquare(1)}
            {this.renderSquare(2)}
          </div>
          <div className="board-row">
            {this.renderSquare(3)}
            {this.renderSquare(4)}
            {this.renderSquare(5)}
          </div>
          <div className="board-row">
            {this.renderSquare(6)}
            {this.renderSquare(7)}
            {this.renderSquare(8)}
          </div>
        </div>
      );
    }
  }
  
  class Game extends React.Component {
    render() {
      return (
        <div className="game">
          <div className="game-board">
            <Board />
          </div>
          <div className="game-info">
            <div>{/* status */}</div>
            <ol>{/* TODO */}</ol>
          </div>
        </div>
      );
    }
  }
  
  // ========================================
  
  const root = ReactDOM.createRoot(document.getElementById("root"));
  root.render(<Game />);

**Comment by scffs** [comment]
Мне кажется, что ты не совсем в нужное место пишешь.
Попробуй спросить в дискорде Реакта https://discord.gg/reactiflux или еще где-нибудь.

**Comment by ntishkevich** [comment]
@Maxim041411 внутри `handleClick` узнаем на какую клетку нажал игрок с помощью аргумента `i`, ставим в эту клетку 'X` и обновляем состояние. А дальше происходит повторный рендеринг и отрисовываем обновленные клетки.
