### ISSUE TITLE
Терминология: phase

### ISSUE THREAD

**Issue by gcor** [reactjs/ru.reactjs.org#91]
The render phase 
(фаза, этап, стадия) рендера

clean up phase
(фаза, этап, стадия) сброса

The commit phase
(фаза, этап, стадия) (фиксирования, применения, правки, коммита)

**Comment by another-guy** [comment]
Мне кажется, это всё подходящие по смыслу синонимы. "Этап" -- самое простое и популярное слово.

![image](https://user-images.githubusercontent.com/5762340/52591668-58b6ea80-2df9-11e9-83b7-f096c4294527.png)

**Comment by lex111** [comment]
@another-guy вау, крутой сервис гугла, не знал про такой :/

**Comment by another-guy** [comment]
@lex111 рад, что хоть что-то можно узнать от меня полезное. 😄

**Comment by gcor** [comment]
Я ещё уточню про commit phase. В документации:
> The commit phase is when React applies any changes. (In the case of React DOM, this is when React inserts, updates, and removes DOM nodes.) React also calls lifecycles like componentDidMount and componentDidUpdate during this phase.

Можно ли это назвать этапом применения? Хотя вариант этап фиксирования наверно более распространён. Но звучит сложнее.

**Comment by lex111** [comment]
> фиксирования

Либо _фиксации_ ещё можно.

**Comment by gaearon** [comment]
Метафора — гит. Мне кажется по-русски уже устоялось «коммит» в этом плане.

Этап рендера и этап коммита были бы ок мне.
