### ISSUE TITLE
Терминология: fallback

### ISSUE THREAD

**Issue by gcor** [reactjs/ru.reactjs.org#92]
fallback

fallback UI
резервный интерфейс
запасной интерфейс

**Comment by another-guy** [comment]
Мне кажется, это всё подходящие по смыслу синонимы. "Этап" -- самое простое и популярное слово.

![image](https://user-images.githubusercontent.com/5762340/52591668-58b6ea80-2df9-11e9-83b7-f096c4294527.png)

**Comment by another-guy** [comment]
Я бы склонялся к "запасной", потому что попроще слово.

Ещё есть вариант "аварийный", но мне как-то режет слух, хотя оно точнее передаёт fallback в значении retreat.

**Comment by lex111** [comment]
А как насчёт _заглушка интерфейса_?

Приведу предложение для примера:
> Update state so the next render will show the fallback UI.

**Comment by another-guy** [comment]
Ну, это не заглушка как таковая. В моём понимании, заглушка

> не несёт никакого осмысленного действия, представляет пустой результат.

А тут это как раз специально спроектрированный UI, который представляет результат-ошибку.

**Comment by lex111** [comment]
Может быть, тогда _альтернативный_, типа такой интерфейс, который показывается в случае, если основной (главный) по каким-либо причинам не отрендерился.

**Comment by gcor** [comment]
Возможно еще подойдет «вспомогательный», правда оно занято helpers.

**Comment by lex111** [comment]
Наверное, и правда лучше всего _запасной_: просто и понятно.

**Comment by another-guy** [comment]
@lex111 мне приходил вариант _альтернативный_ и он мне нравится всем, кроме того, что сложноватое слово и немного общее. Поэтому я не решился его предложить.

**Comment by gcor** [comment]
Я могу сделать реквест?

**Comment by lex111** [comment]
@gcor конечно!
