### ISSUE TITLE
Плашка в страницах про Хуки

### ISSUE THREAD

**Issue by another-guy** [reactjs/ru.reactjs.org#94]
Все :us:/:gb: страницы про Хуки содержат плашку, которая должна быть переведена одинаково на :ru:.

У нас уже есть две конкурирующие версии в пулл реквестах. Надо определиться и использовать один и тот же вариант.

#84 :
> *Хуки* это новое дополнение в React 16.8. Они позволяют вам использовать состояние и другие возможности React без написания классов.

#86 :
> *Хуки* появились в React 16.8. Они позволяют использовать состояние и другие возможности React без необходимости создавать класс.

Или так:
> *Хуки* появились в React 16.8.  Они позволяют использовать состояние и другие возможности React без написания классов.

**Comment by another-guy** [comment]
Над переводами страниц о Хуках работают @pavelkeyzik, @Hisagr, @another-guy, @Hisagr, @airyboy, @tesler. Две страницы пока незастолблены ни за кем.

**Comment by lex111** [comment]
Нравится первый вариант, поскольку ближе к оригиналу, только добавив тире и убрать местоимение.

**Comment by Hisagr** [comment]
Я бы еще предложил заменить **написания -> создания**

**Comment by lex111** [comment]
Но на самом деле не очень ясно (если совершенно не знаешь что это), т.е. вот так:

> _Хуки_ — это новое дополнение в React 16.8. Они позволяют использовать состояние и другие возможности классовых компонентов React без их создания.

лучше всего передаёт суть, хотя выглядит длинно и не очень элегантно (?).

**Comment by Hisagr** [comment]
> 
> 
> Но на самом деле не очень ясно (если совершенно не знаешь что это), т.е. вот так:
> 
> > _Хуки_ — это новое дополнение в React 16.8. Они позволяют использовать состояние и другие возможности классовых компонентов React без их создания.
> 
> лучше всего передаёт суть, хотя выглядит длинно и не очень элегантно (?).

Суть немного искажается все-таки. Ведь только 2 хука покрывают возможности классовых компонентов, а все остальные используют функционал, который не относится к классам.

**Comment by another-guy** [comment]
@lex111 я вынужден согласиться с @Hisagr. Смысл пусть немного, но искажается.

**Comment by pavelkeyzik** [comment]
Может написать что-нибудь вроде "без создания лишних оберток"? Как я понимаю на данный момент для этого хуки и писались 😊

**Comment by airyboy** [comment]
> Нравится первый вариант, поскольку ближе к оригиналу, только добавив тире и убрать местоимение.

"Ближе к оригиналу" можно и в Google Translate посмотреть. И первый вариант, кстати, почти на 100% попал в машинный перевод: https://translate.google.com/#view=home&op=translate&sl=en&tl=ru&text=Hooks%20are%20a%20new%20addition%20in%20React%2016.8.%20They%20let%20you%20use%20state%20and%20other%20React%20features%20without%20writing%20a%20class.

Мне кажется, наша задача перевести нормальным русским языком.

**Comment by another-guy** [comment]
Мне видится, что оба имеющихся варианта несущественно отличаются и мы молем воду в ступе, не?

Меня даже больше волнует первое предложение, чем второе. Я за "_Хуки_ появились в React 16.8.", потому что в другом варианте говорится, что хуки -- новые. Это только сейчас они новые, а через год-два уже нет.

**Comment by lex111** [comment]
> что хуки -- новые

Но указана точная версия, т.е. они новые _относительно_ React 16.8.

Мне нравится "буквальный" перевод, поскольку это хорошее по длине предложение, нежели чем __Хуки_ появились в React 16.8_. В последнем нужно что-то добавить ещё, иначе (как по мне) читается "рвано".

Я, конечно, согласен с @airyboy, хотя в данном случае я не вижу проблем с читабельностью. Можно ещё так:

> > _Хуки_ — новая возможность в React 16.8, которая позволяет использовать состояние и другие возможности React без написания классов.

**Comment by another-guy** [comment]
@lex111 последний предложенный вариант меня устраивает.

**Comment by lex111** [comment]
Перечитал сейчас, и понял, что написал фигню:

> _Хуки_ — новая **возможность** в React 16.8, которая позволяет использовать состояние и другие **возможности** React без написания классов.

Наверное, поэтому имеет смысл использовать _дополнение_ вместо _возможность_? Либо ещё так:

> _Хуки_ — новинка в React 16.8, которая позволяет использовать состояние и другие **возможности** React без написания классов.

**Comment by another-guy** [comment]
@lex111 да, я почему-то проглядел повтор.

**Comment by lex111** [comment]
@ntishkevich предложил ещё вариант _нововведение_ вместо _новинка_ (текущего). Может его будем использовать?

**Comment by another-guy** [comment]
@another-guy мне нравится _!_

Как писать тогда? _Хуки -- нововведение в React 16.8 ..._ ?

**Comment by lex111** [comment]
Верно.
